server:
  port: 8080
spring:
  mail:
    host: smtp.yeah.net
    username: lingfengemail@yeah.net
    password: a123456
    port: 25
    properties:
      mail:
        smtp:
          port: 994
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pinxixi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 2237919313
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    yourdaoclasspackagename: debug
debug: true